services:
  devkitpro:
    build:
      context: .
      dockerfile: ./build_dockerfile
    container_name: devkitpro
    # ports:
    #   - 4405:4405/udp
    volumes:
      - .:/project:cached
    command: make -C /project
    # command: /bin/sh -c "while sleep 1000; do :; done"
