name: PR-Develop

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    name: Deploy development builds (upon pull request)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute build
        run: docker compose -f build-compose.yaml up --abort-on-container-exit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Themiify-dev-pr.wuhb
          path: ./Themiify.wuhb
